# Generated by Django 4.2.4 on 2023-08-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_certificate_shippingdirection_supplier_sticker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='jerecan',
        ),
        migrations.AddField(
            model_name='supplier',
            name='jerecan_sticker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sticker'),
        ),
    ]
