# Generated by Django 4.2.4 on 2023-08-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_sticker_jerecan_supplier_jerecan_sticker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='jerecan_sticker_id',
            new_name='jerecan_sticker',
        ),
    ]
