# Generated by Django 4.2.4 on 2023-08-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_jerecan_sticker_id_supplier_jerecan_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='jerecan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier'),
        ),
    ]
