# Generated by Django 4.2.4 on 2023-08-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_shipping_jerecan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to='mainapp.shippingdirection'),
        ),
    ]
