# Generated by Django 4.2.4 on 2023-08-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_shipping_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsupplier',
            name='jerecan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jerecan_oil', to='mainapp.supplier'),
        ),
    ]
