# Generated by Django 4.2.4 on 2023-09-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_oilsupplier_jerecan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilsupplier',
            name='jerecan',
        ),
        migrations.AddField(
            model_name='supplier',
            name='jerecan_oil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.oilsupplier'),
        ),
    ]
