# Generated by Django 4.2.4 on 2023-09-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_oilsupplier_jerecan_supplier_jerecan_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='jearecane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catoons', to='mainapp.supplier'),
        ),
    ]
