# Generated by Django 4.2.4 on 2023-09-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_cartoon_jearecane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoon',
            name='jearecane',
        ),
        migrations.AddField(
            model_name='supplier',
            name='cartoon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cartoon'),
        ),
    ]
