# Generated by Django 4.2.4 on 2023-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_cartoon_jearecane_supplier_cartoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='grossing',
            field=models.DecimalField(decimal_places=5, default=3, max_digits=10, max_length=10),
        ),
        migrations.AddField(
            model_name='shipping',
            name='margin',
            field=models.DecimalField(decimal_places=5, default=1.5, max_digits=10, max_length=10),
        ),
    ]
